monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.usb-.*"
      }
    ]
    actions = {
      update-props = {
        api.alsa.use-acp = false
         api.acp.auto-port = true
         api.acp.auto-profile = true
      }
    }
  }
]
