#!/bin/zsh

local levels=${1:-1}
if [[ $levels != <-> ]]; then
    echo "Usage: b [number]"
    return 1
fi

local target=""
local i
for (( i = 0; i < levels; i++ )); do
    target+="../"
done
builtin cd -- "$target"
