#!/bin/zsh

if (( ! $+commands[tmux] )); then
    print -P "%F{red}tmux is not installed.%f"
    return 1
fi

local tmux_ls session_name number target session_count input_char
tmux_ls=$(tmux ls 2>/dev/null)
if [[ -z $tmux_ls ]]; then
    print -nP "There is no %F{green}tmux%f session. Input a name to create one (default: %Bdefault%b, %B%F{yellow}[Esc]%f%b to quit): "
    session_name=""
    while true; do
        read -s -k 1 input_char || { echo; return 0; }
        case $input_char in
            $'\e') echo; return 0 ;;
            $'\n'|$'\r') echo; break ;;
            $'\x7f'|$'\b')
                if [[ -n $session_name ]]; then
                    session_name=${session_name[1,-2]}
                    print -n $'\b \b'
                fi
                ;;
            *) session_name+=$input_char; print -n -- "$input_char" ;;
        esac
    done
    [[ -z $session_name ]] && session_name="default"
    if [[ -z $TMUX ]]; then
        exec tmux new-session -s "$session_name"
    fi
    tmux new-session -s "$session_name" -d && tmux switch-client -t "$session_name"
    return $?
fi

tmux_ls=$(tmux ls | awk -F ':' '{print $1}' | nl)
session_count=$(echo "$tmux_ls" | grep -c .)
while true; do
    print -P "Choose a session (%B%F{cyan}[Enter]%f%b selects %B1%b), press %B%F{green}[a]%f%b to create one, or %B%F{yellow}[q]%f%b to quit"
    echo "$tmux_ls" | column -t
    read -k 1 number
    echo

    [[ $number == q ]] && return 0
    [[ -z $number || $number == $'\n' || $number == $'\r' ]] && number=1
    if [[ $number == a || $number == $((session_count + 1)) ]]; then
        while true; do
            print -nP "Input a name for the new %F{green}tmux%f session (default: %Bdefault%b, %B%F{yellow}[Esc]%f%b to cancel): "
            session_name=""
            while true; do
                read -s -k 1 input_char || { echo; break 2; }
                case $input_char in
                    $'\e') echo; break 2 ;;
                    $'\n'|$'\r') echo; break ;;
                    $'\x7f'|$'\b')
                        if [[ -n $session_name ]]; then
                            session_name=${session_name[1,-2]}
                            print -n $'\b \b'
                        fi
                        ;;
                    *) session_name+=$input_char; print -n -- "$input_char" ;;
                esac
            done
            [[ -z $session_name ]] && session_name="default"
            if tmux has-session -t "=$session_name" 2>/dev/null; then
                print -P "%F{red}Session already exists:%f $session_name" >&2
                continue
            fi
            if [[ -z $TMUX ]]; then
                exec tmux new-session -s "$session_name"
            else
                tmux new-session -s "$session_name" -d && tmux switch-client -t "$session_name"
            fi
            return $?
        done
        continue
    fi

    target=$(echo "$tmux_ls" | awk -v number="$number" '$1 == number { print $2 }')
    [[ -n $target ]] && break
    print -P "%F{red}Invalid selection:%f $number" >&2
done

if [[ -z $TMUX ]]; then
    exec tmux attach-session -t "$target"
else
    tmux switch-client -t "$target"
fi
