#!/bin/zsh

if (( ! $+functions[extract] )); then
    echo "extract is not loaded" >&2
    return 1
fi

if (( ! $+commands[unrar] && $+commands[rar] )); then
    setopt localoptions localfunctions
    unrar() {
        command rar "$@"
    }
fi

extract "$@"
