local M = {}
local HOME = os.getenv("HOME")
M.config = {
	output = "",
	mode = "preferred",
	-- position = "0x0",
	scale = nil,
}
---@param m HL.Monitor?
local function valid_monitor(m)
	-- Some monitor will give wrong information after dpms on, meanwhile give an empty description.
	return m and m.id ~= -1 and #m.description > 0
end
function M.get_active_monitor_safe(callback, max_try)
	max_try = max_try or 30
	local monitor = hl.get_active_monitor()
	if valid_monitor(monitor) then
		return callback(monitor)
	end
	local timer
	local try = 0
	timer = hl.timer(function()
		if try >= max_try then
			print("can't find monitor")
			timer:set_enabled(false)
			timer = nil
			return
		end
		local m = hl.get_active_monitor()
		if valid_monitor(m) then
			timer:set_enabled(false)
			timer = nil
			return callback(m)
		end
		try = try + 1
	end, { timeout = 500, type = "repeat" })
end
local scale_tbl = {
	[3840] = {
		[2160] = 2.4,
	},
	[2388] = {
		[1668] = 1.5,
	},
	[2560] = {
		[1440] = 2,
		[1600] = 2,
	},
}
---@param monitor HL.Monitor
local function get_scale(monitor)
	if monitor.scale and monitor.scale > 0 then
		return monitor.scale
	end
	local width = monitor.width
	local height = monitor.height
	if scale_tbl[width] and scale_tbl[width][height] then
		return scale_tbl[width][height]
	end
	return height / 1000
end

local function write_xresources(scale)
	local dpi = math.floor(scale * 96 + 0.5)
	local file = io.open(HOME .. "/.Xresources", "w")
	if not file then
		print("failed to write ~/.Xresources")
		return
	end
	file:write("! This file is generated by ~/.config/hypr/monitor.lua.\n")
	file:write("! Do not edit it manually; changes will be overwritten on Hyprland startup.\n")
	file:write(("Xft.dpi: %d\n"):format(dpi))
	file:close()
	hl.exec_cmd("xrdb -merge ~/.Xresources")
end

function M.setup(opts)
	opts = opts or {}
	for key, value in pairs(opts) do
		M.config[key] = value
	end
	hl.exec_cmd("xrdb -merge ~/.Xresources")
	if not M.config.scale then
		M.get_active_monitor_safe(
			---@param monitor HL.Monitor
			function(monitor)
				M.config.scale = get_scale(monitor)
				write_xresources(M.config.scale)
				hl.monitor(M.config)
			end
		)
	else
		write_xresources(M.config.scale)
		hl.monitor(M.config)
	end
end
return M
