local M = {}
local HOME = os.getenv("HOME")
M.config = {
	output = "",
	mode = "preferred",
	position = "0x0",
	disabled = false,
	scale = nil,
}
---@param m HL.Monitor?
local function valid_monitor(m)
	-- Some monitor will give wrong information after dpms on, meanwhile give an empty description.
	return m and m.id ~= -1 and #m.description > 0
end
function M.get_physic_monitor(callback, max_try)
	max_try = max_try or 30
	for _, monitor in ipairs(hl.get_monitors()) do
		if valid_monitor(monitor) then
			callback(monitor)
			hl.sunshine = require("sunshine")
			return
		end
	end
	local timer
	local try = 0
	timer = hl.timer(function()
		if try >= max_try then
			print("can't find monitor")
			timer:set_enabled(false)
			timer = nil
			return
		end
		for _, monitor in ipairs(hl.get_monitors()) do
			if valid_monitor(monitor) then
				timer:set_enabled(false)
				timer = nil
				callback(monitor)
				hl.sunshine = require("sunshine")
				return
			end
		end
		try = try + 1
	end, { timeout = 500, type = "repeat" })
end
---@param width integer
---@param height integer
---@return number
function M.get_scale(width, height)
	local target_logical_height = 960
	local scale_denominator = 120
	local best_scale
	local best_distance

	for scale_units = scale_denominator, scale_denominator * 3 do
		if width * scale_denominator % scale_units == 0 and height * scale_denominator % scale_units == 0 then
			local logical_height = height * scale_denominator / scale_units
			local distance = math.abs(logical_height - target_logical_height)
			if not best_distance or distance < best_distance then
				best_scale = scale_units / scale_denominator
				best_distance = distance
			end
		end
	end

	return best_scale
end

local function write_xresources(scale)
	local dpi = math.floor(scale * 96 + 0.5)
	local file = io.open(HOME .. "/.Xresources", "w")
	if not file then
		print("failed to write ~/.Xresources")
		return
	end
	file:write("! This file is generated by ~/.config/hypr/monitor.lua.\n")
	file:write("! Do not edit it manually; changes will be overwritten on Hyprland startup.\n")
	file:write(("Xft.dpi: %d\n"):format(dpi))
	file:close()
	hl.exec_cmd("xrdb -merge ~/.Xresources")
end

function M.setup(opts)
	opts = opts or {}
	for key, value in pairs(opts) do
		M.config[key] = value
	end
	hl.exec_cmd("xrdb -merge ~/.Xresources")
	-- if not M.config.scale then
	---@param monitor HL.Monitor
	local function setup_monitor(monitor)
		M.config.scale = M.get_scale(monitor.width, monitor.height)
		M.config.output = monitor.name
		M.default_monitor = monitor
		write_xresources(M.config.scale)
		hl.monitor(M.config)
	end
	M.get_physic_monitor(setup_monitor)
	-- else
	-- 	write_xresources(M.config.scale)
	-- 	hl.monitor(M.config)
	-- end
end
return M
