[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = true
show_symlink = true
scrolloff = 5

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 10000
max_height      = 10000
cache_dir       = ""
image_delay     = 30
image_filter    = "triangle"
image_quality   = 75
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]


[plugin]
prepend_preloaders = [
  # { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "{audio,video}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  { mime = "application/postscript", run = "mediainfo" },
  { url = "/run/user/1000/gvfs/**/*", run = "noop" },
  { url = "/run/media/USER_NAME/**/*", run = "noop" },
  { url = "*.csv", run = "duckdb", multi = false },
  { url = "*.tsv", run = "duckdb", multi = false },
  { url = "*.json", run = "duckdb", multi = false },
  { url = "*.parquet", run = "duckdb", multi = false },
  { url = "*.xlsx", run = "duckdb", multi = false },
]
prepend_previewers = [
  { mime = "{audio,video}/*", run = "mediainfo" },
  # { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  { mime = "application/postscript", run = "mediainfo" },
  { url = "*/", run = "folder" },
  { url = "/run/user/1000/gvfs/**/*", run = "noop" },
  { url = "/run/media/USER_NAME/**/*", run = "noop" },
  { url = "*.csv", run = "duckdb" },
  { url = "*.tsv", run = "duckdb" },
  { url = "*.json", run = "duckdb" },
  { url = "*.parquet", run = "duckdb" },
  { url = "*.xlsx", run = "duckdb" },
  { url = "*.db", run = "duckdb" },
  { url = "*.duckdb", run = "duckdb" },
  { url = "*.docx", run = "docx" },
]
[tasks]
image_alloc = 1073741824 # = 1024*1024*1024 = 1024MB
