#!/bin/zsh
#
# .zshrc - Zsh file loaded on interactive shell sessions.
#

# Enable Powerlevel10k instant prompt. Should stay close to the top of .zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

bindkey -v

export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#b4befe,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 \
--color=selected-bg:#45475a \
--multi"

# Lazy-load (autoload) Zsh function files from a directory.
ZFUNCDIR=${ZDOTDIR:-$HOME}/.zfunctions
fpath=($ZFUNCDIR $fpath)
autoload -Uz $ZFUNCDIR/*(.:t)

# Set any zstyles you might use for configuration.
[[ ! -f ${ZDOTDIR:-$HOME}/.zstyles ]] || source ${ZDOTDIR:-$HOME}/.zstyles

# Clone antidote if necessary.
if [[ ! -d ${ZDOTDIR:-$HOME}/.antidote ]]; then
    git clone --depth=1 https://github.com/mattmc3/antidote ${ZDOTDIR:-$HOME}/.antidote || return 1
fi

# Create an amazing Zsh config using antidote plugins.
source "${ZDOTDIR:-$HOME}/.antidote/antidote.zsh" || return 1
antidote load "${ZDOTDIR:-$HOME}/.zsh_plugins.txt" || return 1

# Source anything in .zshrc.d.
for _rc in ${ZDOTDIR:-$HOME}/.zshrc.d/*.zsh(N); do
    # Ignore tilde files.
    if [[ $_rc:t != '~'* ]]; then
        source "$_rc"
    fi
done
unset _rc

# To customize prompt, run `p10k configure` or edit .p10k.zsh.
[[ ! -f ${ZDOTDIR:-$HOME}/.p10k.zsh ]] || source ${ZDOTDIR:-$HOME}/.p10k.zsh
setopt NO_BEEP
export SUDO_PROMPT=$'[sudo] password for %p: '
if (( $+commands[fzf] )); then
    source <(fzf --zsh)
fi
if (( $+commands[brew] )); then
    _chruby_prefix=$(brew --prefix chruby 2>/dev/null)
    [[ -f "$_chruby_prefix/share/chruby/chruby.sh" ]] && . "$_chruby_prefix/share/chruby/chruby.sh"
    [[ -f "$_chruby_prefix/share/chruby/auto.sh" ]] && . "$_chruby_prefix/share/chruby/auto.sh"
    unset _chruby_prefix
fi
# chruby ruby-3.3.5
[[ -f "$HOME/.cargo/env" ]] && . "$HOME/.cargo/env"
. "${ZDOTDIR:-$HOME}/scripts/baipan/main.zsh"
(( $+commands[micromamba] )) && eval "$(micromamba shell hook --shell zsh)"
return 0
