# 状态栏
StatusBar="Toggle input method"
# 模拟按键释放
SimulateKeyRelease=False
# 模拟按键释放延迟毫秒数
SimulateKeyReleaseDelay=100
# 监视剪贴板
MonitorPasteboard=False
# 清除追踪参数
RemoveTrackingParameters=True
# 轮询剪贴板的间隔（秒）
PollPasteboardInterval=2

[AppDefaultIM]
0="{\"imName\": \"keyboard-us\",\"appId\": \"com.runningwithcrayons.Alfred\",\"appPath\": \"/Applications/Alfred 5.app/\"}"
1="{\"imName\": \"keyboard-us\",\"appPath\": \"/Applications/kitty.app/\",\"appId\": \"net.kovidgoyal.kitty\"}"
2="{\"imName\": \"keyboard-us\",\"appId\": \"app.zen-browser.zen\",\"appPath\": \"/Applications/Zen.app/\"}"
3="{\"appPath\": \"/Applications/QQ.app/\",\"imName\": \"rime\",\"appId\": \"com.tencent.qq\"}"
4="{\"imName\": \"rime\",\"appPath\": \"/Applications/WeChat.app/\",\"appId\": \"com.tencent.xinWeChat\"}"
5="{\"appPath\":\"\\/Applications\\/Moonlight.app\\/\",\"imName\":\"keyboard-us\",\"appId\":\"com.moonlight-stream.Moonlight\"}"

[VimMode]
0=org.vim.MacVim

