hs.ipc = require("hs.ipc")
local util = require("utils")

hs.g = {}
hs.loadSpoon("EmmyLua")
spoon.EmmyLua:init()
require("wifi_mute")
-- require("pasteboard")
-- require("corner")
-- require("rusty")
-- require("vlc")
-- require("test")
require("cmdq")
-- require("window_manager")
require("scripts.caffeine")
-- require("loop")

hs.hotkey.bind({ "cmd" }, "space", function()
	hs.osascript.applescript('tell application "Alfred 5" to search')
end)
local afterboot = require("afterboot")
afterboot()
require("rime")
require("lazy")
-- require("karabiner")
-- hs.karabiner.setup()
-- hs.karabiner.press({ "right_command", "fn" }, "e", function()
-- 	hs.alert("success!")
-- end)
-- hs.karabiner.write()
