// Surfingkeys config.
// Generated by chezmoi from ignore/zen/surfingkeys.js.tmpl.

const skConfig = Object.freeze({
  debug: {{ get . "surfingkeysDebug" | default false }},
});

const skLog = (...args) => {
  if (skConfig.debug) {
    console.info("[surfingkeys-config]", ...args);
  }
};

const skWarn = (...args) => console.warn("[surfingkeys-config]", ...args);

const skEscapeRegExp = (text) => text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const skScriptsByDomain = new Map();

const skDefineScript = ({ name, domains, matches }) => {
  const domainList = (Array.isArray(domains) ? domains : [domains]).map((domain) =>
    domain.toLowerCase()
  );
  const hostPatterns = domainList.map(
    (domain) => new RegExp(`(^|\\.)${skEscapeRegExp(domain)}$`, "i")
  );
  const urlPatterns = domainList.map(
    (domain) => new RegExp(`^https?:\\/\\/([^/]+\\.)?${skEscapeRegExp(domain)}(\\/.*)?`, "i")
  );

  return Object.freeze({
    name,
    domains: domainList,
    hostPattern: hostPatterns[0],
    hostPatterns,
    urlPattern: urlPatterns[0],
    urlPatterns,
    isCurrent: (hostname = location.hostname) =>
      hostPatterns.some((hostPattern) => hostPattern.test(hostname)),
    matchesUrl: (href) => urlPatterns.some((urlPattern) => urlPattern.test(href)),
    matches: matches || (() => true),
  });
};

const skRegisterScript = (metadata, setup) => {
  const script = skDefineScript(metadata);
  const registration = { script, setup };

  script.domains.forEach((domain) => {
    const registrations = skScriptsByDomain.get(domain) || [];
    if (registrations.some(({ script: registeredScript }) => registeredScript.name === script.name)) {
      skWarn(`script registered more than once for ${domain}: ${script.name}`);
    }
    registrations.push(registration);
    skScriptsByDomain.set(domain, registrations);
  });

  return script;
};

const skCurrentScriptRegistrations = (hostname = location.hostname) => {
  const registrations = [];
  const seen = new Set();
  let candidate = hostname.toLowerCase();

  while (candidate) {
    const domainRegistrations = skScriptsByDomain.get(candidate) || [];
    domainRegistrations.forEach((registration) => {
      if (!seen.has(registration.script.name)) {
        registrations.push(registration);
        seen.add(registration.script.name);
      }
    });

    if (domainRegistrations.length > 0) {
      break;
    }

    const dotIndex = candidate.indexOf(".");
    if (dotIndex === -1) {
      break;
    }
    candidate = candidate.slice(dotIndex + 1);
  }

  return registrations;
};

const skRunCurrentScripts = () => {
  const registrations = skCurrentScriptRegistrations();

  registrations.forEach(({ script, setup }) => {
    if (!script.matches({ location, script })) {
      return;
    }

    skLog(`${script.name}: config active`, location.href);
    setup({ script });
  });
};

const skStopEvent = (event) => {
  event.preventDefault();
  event.stopImmediatePropagation();
};
