---@type keybinder
local karabiner = {}
local SHELL = require("wmux.shell")
---@class Karabiner.json.to
---@field shell_command string?
---@field key_code string?
---@field modifiers (table<number,string>)?

---@alias Karabiner.to.key_code string
---@alias Karabiner.to.key_with_mod {[1]:string,[2]:table|integer}
---@alias Karabiner.to.shell SHELL
---@alias Karabiner.to Karabiner.to.key_code|Karabiner.to.key_with_mod|Karabiner.to.shell
karabiner._modifier = {
	shift = 1,
	control = 2,
	command = 4,
	option = 8,
	fn = 16,
}
karabiner.modifier = {
	SHIFT = 1,
	CTRL = 2,
	ALT = 4,
	SUPER = 8,
	FN = 16,
}
karabiner.vitualMod = {}
karabiner._next_vitual_mod_value = 32

function karabiner.mod2int(mods)
	if not mods then
		return 0
	end
	if type(mods) == "number" then
		return mods
	end
	local ret = 0
	if type(mods) == "string" then
		mods = { mods }
	end
	for index, value in ipairs(mods) do
		local mod = karabiner._modifier[value]
		if not mod then
			error("unknown modifier: " .. value)
			break
		end
		ret = ret + mod
	end
	return ret
end

local JSON = require("cjson")
karabiner.condition = {
	always = function()
		return JSON.empty_array
	end,
	not_moonlight = function()
		return karabiner.condition.application_unless("^com\\.moonlight-stream\\.Moonlight$")
	end,
	application = function(applications)
		if type(applications) == "string" then
			applications = { applications }
		end
		return { {
			bundle_identifiers = applications,
			type = "frontmost_application_if",
		} }
	end,
	application_unless = function(applications)
		if type(applications) == "string" then
			applications = { applications }
		end
		return { {
			bundle_identifiers = applications,
			type = "frontmost_application_unless",
		} }
	end,
}
karabiner.rule = {
	description = "auto generated by lua_keymapper",
	manipulators = {},
}
---@type table<integer,lua_keymapper.table>
karabiner.bindlist = {}
for i = 0, 31 do
	karabiner.bindlist[i] = {}
end

function karabiner.int2mods(mod)
	if type(mod) ~= "number" then
		return mod
	end
	local flag = nil
	local ret = {}
	for index, value in pairs(karabiner._modifier) do
		if mod & value ~= 0 then
			flag = true
			ret[#ret + 1] = index
		end
	end
	return flag and ret
end
function karabiner.int2vitualmods(mod)
	if not mod then
		return nil
	end
	local flag = nil
	local ret = {}
	for index, value in pairs(karabiner.vitualMod) do
		if mod & value ~= 0 then
			ret[#ret + 1] = index
			flag = true
		end
	end
	return flag and ret
end

--- Change Karabiner.to into Karabiner.json.to
---@param to Karabiner.to?
---@return Karabiner.json.to?
function karabiner.convert_to(to)
	if not to then
		return
	end
	if type(to) == "string" then
		if to == "fn" then
			return {
				apple_vendor_top_case_key_code = "keyboard_fn",
			}
		else
			return { key_code = to }
		end
	elseif getmetatable(to) == SHELL then
		return to:karabiner()
	else
		to[2] = karabiner.int2mods(to[2])
		if to[1] == "fn" then
			return {
				apple_vendor_top_case_key_code = "keyboard_fn",
				modifiers = to[2],
			}
		else
			return { key_code = to[1], modifiers = to[2] }
		end
	end
end
---@param key string|integer
---@param mod string[]|integer
---@param fn Karabiner.to
---@param priority integer?
---@param conditions table?
karabiner.bind = function(key, mod, fn, conditions, priority)
	local to = karabiner.convert_to(fn)
	mod = karabiner.mod2int(mod)
	priority = priority or 100
	if not conditions then
		priority = 1
		conditions = karabiner.condition.not_moonlight()
	end
	if not karabiner.bindlist[mod][key] then
		karabiner.bindlist[mod][key] = {}
	end
	local i = 1
	while karabiner.bindlist[mod][key][i] do
		if karabiner.bindlist[mod][key][i].priority <= priority then
			break
		end
		i = i + 1
	end
	table.insert(karabiner.bindlist[mod][key], i, { to = to, conditions = conditions, priority = priority })
end

--- Create a vitual modifier with name `name` and key `key`.
---@param key string
---@param name string
---@param overload string|table|SHELL|nil if has any value, this modifier will be lazy, i.e., when press with other key, it will be mod; when pressed alone, it will trig `overload`
function karabiner.createmod(key, name, overload, conditions)
	if not conditions then
		conditions = karabiner.condition.not_moonlight()
	end
	if karabiner._modifier[name] then
		table.insert(karabiner.rule.manipulators, {
			from = {
				key_code = key,
			},
			to = {
				key_code = name ~= "fn" and "left_" .. name or nil,
				apple_vendor_top_case_key_code = name == "fn" and "keyboard_fn" or nil,
				lazy = overload and true,
			},
			to_if_alone = karabiner.convert_to(overload),
			conditions = conditions,
			type = "basic",
		})
		return karabiner._modifier[name]
	elseif karabiner.vitualMod[name] then
		table.insert(karabiner.rule.manipulators, {
			from = {
				key_code = key,
			},
			to = {
				set_variable = {
					name = "vitual_mod_" .. name,
					value = 1,
				},
			},
			to_after_key_up = {
				set_variable = {
					name = "vitual_mod_" .. name,
					value = 0,
				},
			},
			to_if_alone = karabiner.convert_to(overload),
			type = "basic",
		})
		return karabiner.vitualMod[name]
	else
		table.insert(karabiner.rule.manipulators, {
			from = {
				key_code = key,
			},
			to = {
				set_variable = {
					name = "vitual_mod_" .. name,
					value = 1,
				},
			},
			to_after_key_up = {
				set_variable = {
					name = "vitual_mod_" .. name,
					value = 0,
				},
			},
			to_if_alone = karabiner.convert_to(overload),
			type = "basic",
		})
		karabiner.vitualMod[name] = karabiner._next_vitual_mod_value
		karabiner._next_vitual_mod_value = karabiner._next_vitual_mod_value * 2
		for i = karabiner.vitualMod[name], karabiner._next_vitual_mod_value - 1 do
			karabiner.bindlist[i] = {}
		end
		return karabiner.vitualMod[name]
	end
end

function karabiner.print()
	for i = #karabiner.bindlist, 0, -1 do
		local mod = i
		local mod_t = karabiner.bindlist[i]
		for key, key_t in pairs(mod_t) do
			for _, to in ipairs(key_t) do
				local vitualmods = karabiner.int2vitualmods(mod)
				if vitualmods then
					to.conditions = to.conditions or JSON.empty_array
					for _, vitualmod in ipairs(vitualmods) do
						table.insert(to.conditions, {
							name = "vitual_mod_" .. vitualmod,
							type = "variable_if",
							value = 1,
						})
					end
				end
				local phymods = karabiner.int2mods(mod)
				local modifiers = phymods and {
					mandatory = phymods,
				}
				local from
				if key == "fn" then
					from = { apple_vendor_top_case_key_code = "keyboard_fn", modifiers = modifiers }
				else
					from = {
						key_code = key,
						modifiers = modifiers,
					}
				end
				table.insert(karabiner.rule.manipulators, {
					from = from,
					to = to.to,
					to_if_alone = to.to_if_alone,
					to_after_key_up = to.to_after_key_up,
					conditions = to.conditions,
					type = "basic",
				})
			end
		end
	end
	print(JSON.encode(karabiner.rule))
end
return karabiner
