---@type keybinder
local karabiner = {}
local SHELL = require("wmux.shell")
local log = require("wmux.log")
local INVALID = {}
local function warn(message)
	log.warn("karabiner", message)
end
---@class Karabiner.json.to
---@field shell_command string?
---@field key_code string?
---@field modifiers (table<number,string>)?

---@alias Karabiner.to.key_code string
---@alias Karabiner.to.key_with_mod {[1]:string,[2]:table|integer}
---@alias Karabiner.to.shell SHELL
---@alias Karabiner.to Karabiner.to.key_code|Karabiner.to.key_with_mod|Karabiner.to.shell
---@alias condition table|string|string[]
karabiner._modifier = {
	shift = 1,
	control = 2,
	command = 4,
	option = 8,
	fn = 16,
}
karabiner.modifier = {
	SHIFT = 1,
	CTRL = 2,
	ALT = 4,
	SUPER = 8,
	FN = 16,
}
karabiner.feature = {
	createmod = true,
	physicalmod = true,
	virtualmod = true,
}
karabiner.vitualMod = {}
karabiner._next_vitual_mod_value = 32

function karabiner.mod2int(mods)
	if not mods then
		return 0
	end
	if type(mods) == "table" and mods.mod then
		return mods.mod
	end
	if type(mods) == "number" then
		return mods
	end
	local ret = 0
	if type(mods) == "string" then
		mods = { mods }
	end
	for index, value in ipairs(mods) do
		local mod = karabiner._modifier[value]
		if not mod then
			warn("ignoring unknown modifier: " .. value)
			return nil
		end
		ret = ret + mod
	end
	return ret
end

local JSON = require("cjson")
karabiner.condition = {
	always = function()
		return nil
	end,
	not_moonlight = function()
		return karabiner.condition.application_unless("^com\\.moonlight-stream\\.Moonlight$")
	end,
	application = function(applications)
		if type(applications) == "string" then
			applications = { applications }
		end
		return { {
			bundle_identifiers = applications,
			type = "frontmost_application_if",
		} }
	end,
	application_unless = function(applications)
		if type(applications) == "string" then
			applications = { applications }
		end
		return { {
			bundle_identifiers = applications,
			type = "frontmost_application_unless",
		} }
	end,
}
karabiner.rule = {
	description = "auto generated by lua_keymapper",
	manipulators = {},
}
---@type table<integer,lua_keymapper.table>
karabiner.bindlist = {}
for i = 0, 31 do
	karabiner.bindlist[i] = {}
end

function karabiner.int2mods(mod)
	if type(mod) ~= "number" then
		return mod
	end
	local flag = nil
	local ret = {}
	for index, value in pairs(karabiner._modifier) do
		if mod & value ~= 0 then
			flag = true
			ret[#ret + 1] = index
		end
	end
	return flag and ret
end
function karabiner.int2vitualmods(mod)
	if not mod then
		return nil
	end
	local flag = nil
	local ret = {}
	for index, value in pairs(karabiner.vitualMod) do
		if mod & value ~= 0 then
			ret[#ret + 1] = index
			flag = true
		end
	end
	return flag and ret
end

--- Change Karabiner.to into Karabiner.json.to
---@param to Karabiner.to?
---@return Karabiner.json.to?
function karabiner.convert_to(to)
	if not to then
		return
	end
	if type(to) == "string" then
		if to == "fn" then
			return {
				apple_vendor_top_case_key_code = "keyboard_fn",
			}
		else
			return { key_code = to }
		end
	elseif getmetatable(to) == SHELL then
		return to:karabiner()
	elseif type(to) == "function" then
		warn("ignoring runtime Lua action")
		return nil
	else
		local modifiers = karabiner.int2mods(to[2])
		if to[1] == "fn" then
			return {
				apple_vendor_top_case_key_code = "keyboard_fn",
				modifiers = modifiers,
			}
		else
			return { key_code = to[1], modifiers = modifiers }
		end
	end
end

local function normalize_conditions(conditions)
	if not conditions then
		return nil
	end
	if type(conditions) == "string" then
		return karabiner.condition.application(conditions)
	end
	if type(conditions) == "function" then
		warn("ignoring binding with runtime Lua condition")
		return INVALID
	end
	if type(conditions) == "table" and type(conditions[1]) == "string" then
		return karabiner.condition.application(conditions)
	end
	return conditions
end

local function has_fn(mod)
	if not mod then
		return false
	end
	return mod & karabiner.modifier.FN ~= 0
end

local function copy_conditions(conditions)
	local ret = {}
	if type(conditions) ~= "table" then
		return ret
	end
	for i, condition in ipairs(conditions) do
		ret[i] = condition
	end
	return ret
end

local function insert_binding(key, mod, to, conditions, priority)
	if not mod or not to or conditions == INVALID then
		return
	end
	if not karabiner.bindlist[mod][key] then
		karabiner.bindlist[mod][key] = {}
	end
	local i = 1
	while karabiner.bindlist[mod][key][i] do
		if karabiner.bindlist[mod][key][i].priority <= priority then
			break
		end
		i = i + 1
	end
	table.insert(karabiner.bindlist[mod][key], i, { to = to, conditions = conditions, priority = priority })
end

---@param key string|integer
---@param mod string[]|integer
---@param fn Karabiner.to
---@param conditions condition?
---@param priority integer?
---@param opts table? Accepted for API compatibility; Karabiner has no bind flags here.
karabiner.bind = function(key, mod, fn, conditions, priority, opts)
	local to = karabiner.convert_to(fn)
	mod = karabiner.mod2int(mod)
	if not mod or not to then
		return
	end
	local explicit_conditions = conditions ~= nil
	priority = priority or (explicit_conditions and 100 or 1)
	if explicit_conditions then
		conditions = normalize_conditions(conditions)
	elseif not has_fn(mod) then
		conditions = karabiner.condition.not_moonlight()
	end
	insert_binding(key, mod, to, conditions, priority)
	if not explicit_conditions and not has_fn(mod) then
		insert_binding(key, mod + karabiner.modifier.FN, to, nil, priority)
	end
end

--- Create a vitual modifier with name `name` and key `key`.
---@param key string
---@param name string
---@param overload string|table|SHELL|nil if has any value, this modifier will be lazy, i.e., when press with other key, it will be mod; when pressed alone, it will trig `overload`
---@param conditions condition?
function karabiner.createmod(key, name, overload, conditions, fallback)
	local explicit_conditions = conditions ~= nil
	if explicit_conditions then
		conditions = normalize_conditions(conditions)
	else
		conditions = karabiner.condition.not_moonlight()
	end
	local function insert_manipulator(manipulator)
		table.insert(karabiner.rule.manipulators, manipulator)
		if not explicit_conditions then
			local fn_manipulator = {}
			for k, v in pairs(manipulator) do
				fn_manipulator[k] = v
			end
			fn_manipulator.from = {
				key_code = key,
				modifiers = { mandatory = { "fn" } },
			}
			fn_manipulator.conditions = nil
			table.insert(karabiner.rule.manipulators, fn_manipulator)
		end
	end
	if karabiner._modifier[name] then
		if conditions == INVALID then
			return karabiner._modifier[name]
		end
		insert_manipulator({
			from = {
				key_code = key,
			},
			to = {
				key_code = name ~= "fn" and "left_" .. name or nil,
				apple_vendor_top_case_key_code = name == "fn" and "keyboard_fn" or nil,
				lazy = overload and true,
			},
			to_if_alone = karabiner.convert_to(overload),
			conditions = conditions,
			type = "basic",
		})
		return karabiner._modifier[name]
	elseif karabiner.vitualMod[name] then
		if conditions == INVALID then
			return { mod = karabiner.vitualMod[name], fallback = fallback, virtual = true }
		end
		insert_manipulator({
			from = {
				key_code = key,
			},
			to = {
				set_variable = {
					name = "vitual_mod_" .. name,
					value = 1,
				},
			},
			to_after_key_up = {
				set_variable = {
					name = "vitual_mod_" .. name,
					value = 0,
				},
			},
			to_if_alone = karabiner.convert_to(overload),
			conditions = conditions,
			type = "basic",
		})
		return { mod = karabiner.vitualMod[name], fallback = fallback, virtual = true }
	else
		if conditions == INVALID then
			return { fallback = fallback, virtual = true }
		end
		insert_manipulator({
			from = {
				key_code = key,
			},
			to = {
				set_variable = {
					name = "vitual_mod_" .. name,
					value = 1,
				},
			},
			to_after_key_up = {
				set_variable = {
					name = "vitual_mod_" .. name,
					value = 0,
				},
			},
			to_if_alone = karabiner.convert_to(overload),
			conditions = conditions,
			type = "basic",
		})
		karabiner.vitualMod[name] = karabiner._next_vitual_mod_value
		karabiner._next_vitual_mod_value = karabiner._next_vitual_mod_value * 2
		for i = karabiner.vitualMod[name], karabiner._next_vitual_mod_value - 1 do
			karabiner.bindlist[i] = {}
		end
		return { mod = karabiner.vitualMod[name], fallback = fallback, virtual = true }
	end
end

function karabiner.print()
	for i = #karabiner.bindlist, 0, -1 do
		local mod = i
		local mod_t = karabiner.bindlist[i]
		for key, key_t in pairs(mod_t) do
			for _, to in ipairs(key_t) do
				local vitualmods = karabiner.int2vitualmods(mod)
				local conditions = to.conditions
				if vitualmods then
					conditions = copy_conditions(to.conditions)
					for _, vitualmod in ipairs(vitualmods) do
						table.insert(conditions, {
							name = "vitual_mod_" .. vitualmod,
							type = "variable_if",
							value = 1,
						})
					end
				end
				local phymods = karabiner.int2mods(mod)
				local modifiers = phymods and {
					mandatory = phymods,
				}
				local from
				if key == "fn" then
					from = { apple_vendor_top_case_key_code = "keyboard_fn", modifiers = modifiers }
				else
					from = {
						key_code = key,
						modifiers = modifiers,
					}
				end
				table.insert(karabiner.rule.manipulators, {
					from = from,
					to = to.to,
					to_if_alone = to.to_if_alone,
					to_after_key_up = to.to_after_key_up,
					conditions = conditions,
					type = "basic",
				})
			end
		end
	end
	print(JSON.encode(karabiner.rule))
end
return karabiner
